# Generated by Django 5.1.7 on 2025-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('is_sustainable', models.BooleanField(default=False)),
            ],
        ),
    ]
