# Generated by Django 4.2 on 2025-06-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='name',
        ),
        migrations.AddField(
            model_name='companydata',
            name='has_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='is_sustainable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='revenue',
            field=models.FloatField(help_text='Annual revenue in local currency'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='sector',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('IT', 'IT')], max_length=50),
        ),
    ]
