# Generated by Django 5.1.7 on 2025-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_companydata_name_companydata_has_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='waste_amount',
            field=models.FloatField(blank=True, help_text='Waste produced per year (kg)', null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='waste_type',
            field=models.CharField(blank=True, help_text='E.g. Plastic, Organic, Electronic', max_length=100, null=True),
        ),
    ]
