# Generated by Django 4.2 on 2025-06-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companydata_waste_amount_companydata_waste_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='revenue',
        ),
    ]
