# Generated by Django 4.2 on 2025-06-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_companydata_employee_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='name',
            field=models.CharField(default='company', help_text='Company name', max_length=200),
        ),
        migrations.AddField(
            model_name='companydata',
            name='predicted_waste_next_year',
            field=models.FloatField(blank=True, help_text='Estimated waste next year (kg)', null=True),
        ),
    ]
