# Generated by Django 4.2 on 2025-06-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companydata_date_recorded_companydata_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='reduced_waste_due_to_recommendation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='yearly_produced_waste',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='name',
            field=models.CharField(default='Unknown', help_text='Company name', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='predicted_waste_next_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='waste_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='waste_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
