export const mockUsers = [
  {
    "id": 1,
    "name": "EcoTech Pvt. Ltd.",
    "email": "eco@tech.com",
    "password": "eco123",
    "sector": "Tech",
    "totalProducts": 200,
    "waste_type": "Electronic",
    "is_sustainable": true,
    "isSubscribed": false,
    "totalMaterials": 500,
    "phone": "01-4412345",
    "waste_amount": 300
  },
  {
    "id": 2,
    "name": "AgroNepal",
    "email": "contact@agronepal.com",
    "password": "agro321",
    "sector": "Agriculture",
    "totalProducts": 120,
    "waste_type": "Organic",
    "is_sustainable": false,
    "isSubscribed": false,
    "totalMaterials": 500,
    "phone": "021-5267890",
    "waste_amount": 380
  },
  {
    "id": 3,
    "name": "Himalayan Plastics",
    "email": "info@himplast.com",
    "password": "plast!456",
    "sector": "Manufacturing",
    "totalProducts": 500,
    "waste_type": "Plastic",
    "is_sustainable": false,
    "isSubscribed": false,
    "totalMaterials": 500,
    "phone": "01-4211987",
    "waste_amount": 0
  },
  {
    "id": 4,
    "name": "GreenMart",
    "email": "support@greenmart.com",
    "password": "green1234",
    "sector": "Retail",
    "totalProducts": 90,
    "waste_type": "Mixed",
    "is_sustainable": true,
    "isSubscribed": false,
    "totalMaterials": 500,
    "phone": "01-4536789",
    "waste_amount": 410
  },
  {
    "id": 5,
    "name": "Pushkar Niraula",
    "email": "123@gmail.com",
    "password": "123456",
    "isSubscribed": false,
    "totalProducts": 0,
    "totalMaterials": 0,
    "waste_type": "",
    "is_sustainable": false,
    "waste_amount": 0
  }
];